#!/usr/bin/env bash
# simpleviz installer — installs the latest GitHub release into
# ~/.simpleviz (a directory this installer fully manages: reinstalls
# replace it) and a launcher into ~/.local/bin/simpleviz.
#
#   curl -fsSL https://raw.githubusercontent.com/sstoehrm/simpleviz/main/install.sh | bash
#
# Env overrides: SIMPLEVIZ_HOME (default ~/.simpleviz),
#                SIMPLEVIZ_BIN  (default ~/.local/bin)
set -euo pipefail

REPO="sstoehrm/simpleviz"
API_URL="https://api.github.com/repos/$REPO/releases/latest"
SIMPLEVIZ_HOME="${SIMPLEVIZ_HOME:-$HOME/.simpleviz}"
BIN_DIR="${SIMPLEVIZ_BIN:-$HOME/.local/bin}"
MIN_BB="1.12.0"

die() { echo "install: $*" >&2; exit 1; }

check_deps() {
  local c have
  for c in curl tar; do
    command -v "$c" >/dev/null 2>&1 || die "$c is required"
  done
  command -v bb >/dev/null 2>&1 \
    || die "babashka (bb) not found — install it from https://babashka.org"
  have=$(bb --version | sed -E 's/[^0-9.]//g')
  [ "$(printf '%s\n' "$MIN_BB" "$have" | sort -V | head -n1)" = "$MIN_BB" ] \
    || die "babashka $have is too old (need >= $MIN_BB)"
}

# babashka loads nothing from a classpath entry whose path holds a %
# (#99): the install folder and the Maven cache where bb keeps the
# libraries must not have one. That cache is under Java's user.home (the
# account's home, whatever $HOME says), so ask bb for it.
check_paths() {
  local m2
  case "$SIMPLEVIZ_HOME" in *%*)
    die "$SIMPLEVIZ_HOME contains a %, and babashka can't load code from such a path — set SIMPLEVIZ_HOME to a path without one" ;;
  esac
  m2="$(bb -e '(print (System/getProperty "user.home"))')/.m2"
  case "$m2" in *%*)
    die "$m2 contains a %, and babashka can't load code from such a path — it keeps simpleviz's libraries there" ;;
  esac
}

fetch_release() { # sets TAG and TARBALL_URL
  local json
  json=$(curl -fsSL "$API_URL") || die "could not query $API_URL"
  TAG=$(grep -m1 '"tag_name"' <<<"$json" | sed -E 's/.*: *"([^"]+)".*/\1/' || true)
  TARBALL_URL=$(grep -m1 -o '"browser_download_url" *: *"[^"]*\.tar\.gz"' <<<"$json" \
                | sed -E 's/.*"(https[^"]+)".*/\1/' || true)
  [ -n "$TAG" ] && [ -n "$TARBALL_URL" ] \
    || die "no .tar.gz asset found in the latest release"
}

install_files() {
  local dir
  # deliberately not `local`: the EXIT trap runs after this function's
  # scope is gone, so the variable must survive it
  tmp=$(mktemp -d)
  trap 'rm -rf "$tmp"' EXIT
  echo "downloading $TARBALL_URL"
  curl -fsSL "$TARBALL_URL" -o "$tmp/bundle.tar.gz"
  tar xzf "$tmp/bundle.tar.gz" -C "$tmp"
  dir=$(find "$tmp" -mindepth 1 -maxdepth 1 -type d | head -n1)
  [ -n "$dir" ] || die "unexpected tarball layout (no top-level directory)"
  # the launcher below execs the release's `cli` namespace; a release
  # from before it needs the installer it shipped with
  [ -f "$dir/server/cli.clj" ] \
    || die "release $TAG predates this installer — install it with its own: curl -fsSL https://raw.githubusercontent.com/$REPO/$TAG/install.sh | bash"
  rm -rf "$SIMPLEVIZ_HOME"
  mkdir -p "$SIMPLEVIZ_HOME"
  cp -R "$dir"/. "$SIMPLEVIZ_HOME"/
  echo "$TAG" >"$SIMPLEVIZ_HOME/VERSION"
}

write_launcher() {
  mkdir -p "$BIN_DIR"
  cat >"$BIN_DIR/simpleviz" <<'LAUNCHER'
#!/usr/bin/env bash
# simpleviz launcher — generated by install.sh; reinstalling overwrites it.
# It keeps the commands that belong to this install (update, clean-all) and
# hands everything else to the babashka CLI in $SIMPLEVIZ_HOME (namespace
# `cli`), run from the caller's folder.
set -euo pipefail

SIMPLEVIZ_HOME="${SIMPLEVIZ_HOME:-$HOME/.simpleviz}"
API_URL="https://api.github.com/repos/sstoehrm/simpleviz/releases/latest"
MIN_BB="1.12.0"

die() { echo "simpleviz: $*" >&2; exit 1; }

check_bb() {
  local have
  command -v bb >/dev/null 2>&1 \
    || die "babashka (bb) not found — install it from https://babashka.org"
  have=$(bb --version | sed -E 's/[^0-9.]//g')
  [ "$(printf '%s\n' "$MIN_BB" "$have" | sort -V | head -n1)" = "$MIN_BB" ] \
    || die "babashka $have is too old (need >= $MIN_BB)"
}

# babashka loads nothing from a classpath entry whose path holds a %:
# neither this install nor the Maven cache with its libraries (under
# Java's user.home, whatever $HOME says) may have one
check_paths() {
  local m2
  case "$SIMPLEVIZ_HOME" in *%*)
    die "$SIMPLEVIZ_HOME contains a %, and babashka can't load code from such a path — reinstall with SIMPLEVIZ_HOME set to a path without one" ;;
  esac
  m2="$(bb -e '(print (System/getProperty "user.home"))')/.m2"
  case "$m2" in *%*)
    die "$m2 contains a %, and babashka can't load code from such a path — it keeps simpleviz's libraries there" ;;
  esac
}

version() { cat "$SIMPLEVIZ_HOME/VERSION" 2>/dev/null || echo "unknown"; }

update() {
  local latest installer
  latest=$(curl -fsSL "$API_URL" | grep -m1 '"tag_name"' \
           | sed -E 's/.*: *"([^"]+)".*/\1/') \
    || die "could not query the latest release"
  [ -n "$latest" ] || die "could not read the latest release tag"
  if [ "$latest" = "$(version)" ]; then
    echo "simpleviz $(version) is already up to date"
  else
    echo "updating $(version) -> $latest"
    # run the new release's installer, never a stored copy: an installer
    # writes the launcher embedded in itself, so an old one would keep
    # reinstalling its old launcher next to the new files
    installer=$(mktemp)
    curl -fsSL "https://raw.githubusercontent.com/sstoehrm/simpleviz/$latest/install.sh" \
      -o "$installer" || { rm -f "$installer"; die "could not download the $latest installer"; }
    SIMPLEVIZ_HOME="$SIMPLEVIZ_HOME" bash "$installer"
    rm -f "$installer"
  fi
}

clean_all() {
  local procs line pid found=0
  command -v pgrep >/dev/null 2>&1 || die "clean-all needs pgrep"
  # every CLI process of this install runs with exactly this --config;
  # only serve and demo keep running
  procs=$(pgrep -af -- "--config $SIMPLEVIZ_HOME/bb.edn -m cli" || true)
  while IFS= read -r line; do
    [ -n "$line" ] || continue
    pid=${line%% *}
    found=1
    echo "killing ${line#* }"
    kill "$pid" 2>/dev/null || true
  done <<<"$procs"
  [ "$found" -eq 1 ] || echo "simpleviz: no running servers"
}

case "${1:-}" in
  update) update ;;
  clean-all) clean_all ;;
  *)
    check_bb
    check_paths
    [ -d "$SIMPLEVIZ_HOME" ] || die "$SIMPLEVIZ_HOME not found — run install.sh first"
    exec bb --config "$SIMPLEVIZ_HOME/bb.edn" -m cli "$@"
    ;;
esac
LAUNCHER
  chmod +x "$BIN_DIR/simpleviz"
}

main() {
  check_deps
  check_paths
  fetch_release
  install_files
  write_launcher
  case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) echo "note: $BIN_DIR is not on your PATH — add it to use 'simpleviz'" ;;
  esac
  echo "installed simpleviz $TAG"
  echo "  files:    $SIMPLEVIZ_HOME"
  echo "  launcher: $BIN_DIR/simpleviz"
  echo "try: simpleviz demo"
}

if [ "${SIMPLEVIZ_INSTALL_SOURCED:-}" != "1" ]; then
  main "$@"
fi
